version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - ./.env
    networks:
      - mynetwork
    ports:
      - 3306:3306

  webapp:
    container_name: web_app
    build: .
    restart: always
    command: sh -c "python manage.py migrate && test -d static || mkdir static && python manage.py collectstatic --noinput && gunicorn -w 1 -k uvicorn.workers.UvicornWorker 'giterview.asgi:application' --bind=0.0.0.0:8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      # - mysql
      - rabbit
    networks:
      - mynetwork
    volumes:
      - ./:/usr/src/app
      - shared_volume:/tmp

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork

  celery:
    container_name: celery_worker
    build: .
    command: sh -c "celery -A celery_worker worker -l info"
    depends_on:
      - rabbit
      - redis
    networks:
      - mynetwork
    volumes:
      # - ./celery_worker:/usr/src/app/celery_worker
      - shared_volume:/tmp
      - ./:/usr/src/app

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  shared_volume:
